Add RiftProcessorTest and update Rift Processor to no longer bomb whe…
chrischen86/Hudson pull request #61
Opened 2018-03-27 05:31 UTC by uofirob

Add RiftProcessorTest and update Rift Processor to no longer bomb when you start a rift with only the time set.

2018-03-27 05:32 UTC, uofirob commented
I finally got the tests working, but I need you to look at how to check the output of the process to verify that it created the correct rift in the test.  Other than that, I think I fixed the bug where if you create a rift with no type but a time that it shows blank (now it will check and if 1, it is assumed it's the time value)

2018-03-28 03:22 UTC, chrischen86 requested changes
I pushed a commit with an example of how you can test for attachments and other properties not declared public by testing parameters of the mock we setup.

Can you assert the rest and make sure it is good?

2018-03-28 04:42 UTC, uofirob commented
Ok let's see if this worked (Closed newer PR)

2018-03-28 04:43 UTC, chrischen86 approved these changes

2018-03-28 04:43 UTC, merged